import { randomUUID } from 'node:crypto';
import type { AgonModFactory, CommandResult, Dispose, InvocationContext, Json, ModServices, Registrar } from '@kernlang/agon-mod-api';
import { createPersistenceEnvelope } from '@kernlang/agon-support-persistence';

export type JobState = 'queued'|'running'|'succeeded'|'failed'|'cancelled';
export interface JobSnapshot { id:string; kind:string; label:string; state:JobState; createdAt:string; startedAt?:string; finishedAt?:string; error?:string }
export interface JobEvent { seq:number; ts:number; type:string; data?:Json }
export interface JobOutcome { state:'succeeded'|'failed'|'cancelled'; value?:Json; error?:string }
export interface JobTaskContext { signal:AbortSignal; emit:(type:string,data?:Json)=>void }
type JobRecordInternal = { snapshot:JobSnapshot; events:JobEvent[]; controller:AbortController; task:((context:JobTaskContext)=>Promise<Json>)|null; outcome:JobOutcome|null; waiters:Array<(outcome:JobOutcome)=>void>; settled:boolean };
const terminal=(state:JobState)=>state==='succeeded'||state==='failed'||state==='cancelled';

/** Process-owned bounded scheduler. Durable state is an observation ledger, never an executable closure. */
export class ModularJobService {
  private readonly records=new Map<string,JobRecordInternal>(); private readonly queue:string[]=[]; private active=0;
  constructor(private readonly services:ModServices,private readonly maxConcurrency=2,private readonly eventLimit=1000,private readonly retentionLimit=100){}
  submit(kind:string,label:string,task:(context:JobTaskContext)=>Promise<Json>):JobSnapshot{kind=kind.trim();if(!kind)throw new Error('Job kind must not be empty');const id=randomUUID();const snapshot:JobSnapshot={id,kind,label:label.trim()||kind,state:'queued',createdAt:new Date().toISOString()};const record:JobRecordInternal={snapshot,events:[],controller:new AbortController(),task,outcome:null,waiters:[],settled:false};this.records.set(id,record);this.event(record,'queued');this.queue.push(id);void this.persist(record);this.pump();return{...snapshot};}
  get(id:string){const value=this.records.get(id);return value?{...value.snapshot}:undefined;}
  list(){return[...this.records.values()].map(x=>({...x.snapshot})).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));}
  events(id:string,after=0,limit=100){const r=this.records.get(id);if(!r)return undefined;const bounded=Math.max(1,Math.min(this.eventLimit,limit));const earliestSeq=r.events[0]?.seq??1;const events=r.events.filter(x=>x.seq>after).slice(0,bounded).map(x=>({...x}));return{jobId:id,events,nextSeq:events.at(-1)?.seq??after,earliestSeq,terminal:terminal(r.snapshot.state),truncated:after<earliestSeq-1};}
  result(id:string){const r=this.records.get(id);return r?r.outcome?{...r.outcome}:null:undefined;}
  wait(id:string):Promise<JobOutcome|undefined>{const r=this.records.get(id);if(!r)return Promise.resolve(undefined);if(r.outcome)return Promise.resolve({...r.outcome});return new Promise(resolve=>r.waiters.push(value=>resolve({...value})));}
  cancel(id:string,reason='Cancelled'){const r=this.records.get(id);if(!r||terminal(r.snapshot.state))return false;const wasQueued=r.snapshot.state==='queued';r.controller.abort(reason);this.finish(r,'cancelled',undefined,reason);if(wasQueued&&r.task){this.queue.splice(0,this.queue.length,...this.queue.filter(x=>x!==id));r.task=null;r.settled=true;}this.resolve(r);void this.persist(r);this.pump();return true;}
  private event(r:JobRecordInternal,type:string,data?:Json){const event:JobEvent={seq:(r.events.at(-1)?.seq??0)+1,ts:Date.now(),type};if(data!==undefined)event.data=data;r.events.push(event);if(r.events.length>this.eventLimit)r.events.splice(0,r.events.length-this.eventLimit);}
  private finish(r:JobRecordInternal,state:'succeeded'|'failed'|'cancelled',value?:Json,error?:string){if(terminal(r.snapshot.state))return;r.snapshot={...r.snapshot,state,finishedAt:new Date().toISOString(),...(error?{error}:{})};r.outcome={state,...(value!==undefined?{value}:{}),...(error?{error}:{})};this.event(r,state,error?{error}:value);}
  private resolve(r:JobRecordInternal){if(!r.outcome)return;for(const waiter of r.waiters.splice(0))waiter(r.outcome);}
  private async persist(r:JobRecordInternal){const payload=JSON.parse(JSON.stringify({snapshot:r.snapshot,events:r.events,outcome:r.outcome}))as Json;const envelope=createPersistenceEnvelope({kind:'job',status:r.snapshot.state,payload,idSeed:r.snapshot.id,ownerModId:'agon.jobs',ownerModVersion:this.services.identity.version,ownerContentHash:this.services.identity.contentHash,contributionId:'agon.jobs.persisted-job',createdAt:r.snapshot.createdAt,updatedAt:r.snapshot.finishedAt??r.snapshot.startedAt??r.snapshot.createdAt});await this.services.state.write(`jobs/${r.snapshot.id}`,envelope as unknown as Json);}
  private pump(){while(this.active<this.maxConcurrency&&this.queue.length){const id=this.queue.shift()!;const r=this.records.get(id);if(!r||r.snapshot.state!=='queued'||!r.task)continue;this.active++;r.snapshot={...r.snapshot,state:'running',startedAt:new Date().toISOString()};this.event(r,'started');void this.persist(r);const task=r.task;Promise.resolve().then(()=>task({signal:r.controller.signal,emit:(type,data)=>{if(!terminal(r.snapshot.state)){this.event(r,type,data);void this.persist(r);}}})).then(value=>this.finish(r,'succeeded',value)).catch(error=>this.finish(r,r.controller.signal.aborted?'cancelled':'failed',undefined,error instanceof Error?error.message:String(error))).finally(()=>{r.task=null;r.settled=true;this.active--;this.resolve(r);void this.persist(r);this.prune();this.pump();});}}
  private prune(){const done=[...this.records.values()].filter(r=>r.settled&&terminal(r.snapshot.state)).sort((a,b)=>(a.snapshot.finishedAt??'').localeCompare(b.snapshot.finishedAt??''));for(const r of done.slice(0,Math.max(0,done.length-this.retentionLimit)))this.records.delete(r.snapshot.id);}
}

const schema=Object.freeze({type:'object',additionalProperties:true,properties:{jobId:{type:'string'},kind:{type:'string'},label:{type:'string'},prompt:{type:'string'},engine:{type:'string'},after:{type:'number'},limit:{type:'number'},reason:{type:'string'},_:{type:'array',items:{type:'string'}}}})as Readonly<Record<string,Json>>;
const actions:Record<string,string>={'cliCommands:0015':'daemon','cliCommands:0026':'list','cliCommands:0027':'cancel','cliCommands:0028':'events','cliCommands:0029':'list','cliCommands:0030':'result','cliCommands:0031':'status','cliCommands:0032':'submit','mcpTools:0010':'cancel','mcpTools:0011':'events','mcpTools:0012':'list','mcpTools:0013':'result','mcpTools:0014':'status','mcpTools:0015':'submit','intentVariants:0031':'focus','intentVariants:0038':'list','builtinCommandMetadata:0024':'focus','builtinCommandMetadata:0029':'list','tuiSlashCommands:0032':'focus','tuiSlashCommands:0040':'list'};
async function operate(action:string,input:Json,context:InvocationContext,services:ModServices,jobs:ModularJobService):Promise<CommandResult>{const x=input as Record<string,Json>;const id=String(x.jobId??'').trim();let result:Json;
  if(action==='submit'){const kind=String(x.kind??'ask').trim();const prompt=String(x.prompt??'').trim();const engine=String(x.engine??'').trim()||[...(await services.engines.listActive?.(context)??[])][0];if(!prompt||!engine)return{exitCode:1,stderr:'Job submit requires prompt and an active engine.\n'};result=jobs.submit(kind,String(x.label??prompt.slice(0,80)),async job=>{const value=await services.engines.dispatch(engine,prompt,{...context,signal:job.signal},{mode:'agent'});job.emit('result',value);return value;}) as unknown as Json;}
  else if(action==='list'||action==='daemon')result=jobs.list() as unknown as Json;
  else if(action==='status'||action==='focus'){const value=jobs.get(id);if(!value)return{exitCode:1,stderr:`Job not found: ${id}\n`};result=value as unknown as Json;}
  else if(action==='events'){const value=jobs.events(id,Number(x.after??0),Number(x.limit??100));if(!value)return{exitCode:1,stderr:`Job not found: ${id}\n`};result=value as unknown as Json;}
  else if(action==='result'){const value=jobs.result(id);if(value===undefined)return{exitCode:1,stderr:`Job not found: ${id}\n`};result=(value??{state:'running'}) as unknown as Json;}
  else if(action==='cancel'){result={cancelled:jobs.cancel(id,String(x.reason??'Cancelled'))};}
  else return{exitCode:1,stderr:`Unknown job action: ${action}\n`};return{exitCode:0,stdout:`${JSON.stringify(result,null,2)}\n`,result};}
export const createMod:AgonModFactory=services=>{const jobs=new ModularJobService(services);return Object.freeze({apiVersion:'1'as const,async activate(registrar:Registrar):Promise<Dispose>{const d:Dispose[]=[];for(const[id,action]of Object.entries(actions)){const run=(input:Json,context:InvocationContext)=>operate(action,input,context,services,jobs);if(id.startsWith('mcpTools:'))d.push(registrar.tool('mcp',{id,description:`${action} a bounded background job`,inputSchema:schema,effect:action==='list'||action==='status'||action==='events'||action==='result'?'read':'process',run:async(i,c)=>{const o=await run(i,c);if(o.exitCode)throw new Error(o.stderr??'Job operation failed');return o.result??{};}}));else if(id.startsWith('intentVariants:'))d.push(registrar.intent({id,description:`${action} a background job`,inputSchema:schema,parse:value=>{const parts=value.trim().split(/\s+/);if(action==='list'&&parts[0]?.toLowerCase()==='/jobs'){const requested=parts[1]?.toLowerCase();return{action:requested==='cancel'?'cancel':'list',jobId:requested==='cancel'?parts[2]:undefined};}if(action==='focus'&&parts[0]?.toLowerCase()==='/focus')return{jobId:parts.slice(1).join(' ')||undefined};return undefined;},run}));else d.push(registrar.command(id.startsWith('cliCommands:')?'cli':'tui',{id,description:`${action} a bounded background job`,inputSchema:schema,run}));}for(const id of['resultAndEnvelopeTypes:0040','resultAndEnvelopeTypes:0071','resultAndEnvelopeTypes:0072','resultAndEnvelopeTypes:0073'])d.push(registrar.resultType({id,schema,readableVersions:'>=0.2.0',render:async payload=>({text:JSON.stringify(payload,null,2)})}));return async()=>{for(const job of jobs.list())jobs.cancel(job.id,'Jobs mod disabled');for(const dispose of[...d].reverse())await dispose();};}});};
export default createMod;
