import { commandResultToToolResult } from '@kernlang/agon-mod-api';
export const PIPELINE_ORCHESTRATION_WORKFLOW = Object.freeze({
  id: 'agon.workflow.pipeline-orchestration.v1',
  compatibilityAliases: Object.freeze(['mcp:Pipeline']),
  stages: Object.freeze(['brainstorm', 'forge', 'tribunal']),
});

import type{AgonModFactory,CommandResult,Dispose,InvocationContext,Json,ModServices,Registrar}from'@kernlang/agon-mod-api';import{runBrainstorm}from'@kernlang/agon-mod-brainstorm';import{runForgeCompetition}from'@kernlang/agon-mod-forge';import{runTribunal}from'@kernlang/agon-mod-tribunal';
const schema=Object.freeze({type:'object',additionalProperties:true,properties:{task:{type:'string'},test:{type:'string'},engines:{type:'string'},timeout:{type:'string'},_:{type:'array',items:{type:'string'}}}})as Readonly<Record<string,Json>>;const text=(v:Json|undefined)=>typeof v==='string'?v.trim():'';
export async function runOrchestrationPipeline(raw:Json,context:InvocationContext,services:ModServices):Promise<CommandResult>{const input=raw as Record<string,Json>;const task=text(input.task)||(Array.isArray(input._)?input._.map(String).join(' ').trim():'');if(!task)return{exitCode:1,stderr:'Pipeline requires a task.\n'};const stages:any[]=[];const brainstorm=await runBrainstorm({question:`Before implementation, identify requirements, risks, edge cases, and verification for: ${task}`,engines:input.engines??'',timeout:input.timeout??'120'},context,services);stages.push({stage:'brainstorm',exitCode:brainstorm.exitCode,result:brainstorm.result??null});if(brainstorm.exitCode!==0)return{exitCode:1,stderr:'Pipeline brainstorm stage failed.\n',result:{task,stages}as unknown as Json};const brief=brainstorm.result&&typeof brainstorm.result==='object'&&!Array.isArray(brainstorm.result)?String((brainstorm.result as any).response??''):'';const forge=await runForgeCompetition({task:`${task}\n\nDISCOVERY BRIEF:\n${brief}`,test:text(input.test),engines:input.engines??'',timeout:input.timeout??'600',baselineMayPass:true},context,services);stages.push({stage:'forge',exitCode:forge.exitCode,result:forge.result??null});if(forge.exitCode!==0)return{exitCode:1,stderr:'Pipeline Forge stage produced no passing candidate.\n',result:{task,stages}as unknown as Json};const f=forge.result as Record<string,Json>;const tribunal=await runTribunal({question:`Adversarially assess whether this Forge result satisfies the task and whether the evidence is sufficient.\nTASK: ${task}\nWINNER: ${String(f?.winner??'')}\nPATCH:\n${String(f?.winningPatch??'')}`,engines:input.engines??'',mode:'red-team',rounds:'1',timeout:input.timeout??'120'},context,services);stages.push({stage:'tribunal',exitCode:tribunal.exitCode,result:tribunal.result??null});const ok=tribunal.exitCode===0;const result={task,status:ok?'completed':'review_failed',stages,winner:f?.winner??null,winningPatch:f?.winningPatch??null};const receiptId=await services.receipts.record('pipeline-orchestration',result as unknown as Json);return{exitCode:ok?0:1,stdout:`${JSON.stringify({...result,receiptId},null,2)}\n`,result:{...result,receiptId}as unknown as Json};}
export const createMod:AgonModFactory=services=>Object.freeze({apiVersion:'1'as const,async activate(registrar:Registrar):Promise<Dispose>{const d=registrar.tool('mcp',{id:'mcpTools:0016',description:'Run brainstorm → isolated Forge → adversarial verification',inputSchema:schema,effect:'process',run:async(input,context)=>{const out=await runOrchestrationPipeline(input,context,services);return commandResultToToolResult(out);}});return async()=>d();}});export default createMod;
