import { describe, expect, it, vi } from 'vitest';
import type { CommandContribution, ModServices, Registrar } from '@kernlang/agon-mod-api';
import { createMod } from './implementation.js';
const context = { invocationId: 'council-test', cwd: process.cwd(), platform: 'darwin-arm64' as const, signal: new AbortController().signal, config: {} };
async function setup() { const dispatch = vi.fn(async (engineId: string, prompt: string) => ({ engineId, exitCode: 0, stdout: prompt.includes('Synthesize one accountable') ? 'RECOMMENDATION\nConfidence: 73%\nShip with a kill-switch.' : prompt.includes('Frame this') ? 'DECISION: ship\nOPTIONS: yes/no' : `${engineId} analysis`, stderr: '', timedOut: false })); const record = vi.fn(async () => 'receipt'); const services = { identity: { id: 'agon.council', version: '1.0.0', contentHash: `sha256:${'a'.repeat(64)}` }, source: 'bundled', logger: { debug: vi.fn(), info: vi.fn(), warn: vi.fn() }, receipts: { record }, permissions: { check: vi.fn(async () => 'allow') }, state: { read: vi.fn(), write: vi.fn() }, engines: { listActive: vi.fn(async () => ['alpha', 'beta', 'gamma']), rank: vi.fn(async () => [{ engineId: 'gamma', reason: 'top-rated', scope: 'tribunal' }, { engineId: 'alpha', reason: 'top-rated', scope: 'global' }, { engineId: 'beta', reason: 'random', scope: null }]), dispatch } } as unknown as ModServices; let command: CommandContribution | undefined; const registrar = { command: (surface: string, value: CommandContribution) => { if (surface === 'cli') command = value; return () => {}; }, tool: () => () => {}, planStep: () => () => {} } as unknown as Registrar; const mod = await createMod(services); await mod.activate(registrar, services); return { command: command!, dispatch, record }; }
describe('physical council mod', () => {
  it('runs brief, advisor, directed-critique, and chairman phases', async () => { const h = await setup(); const result = await h.command.run({ question: 'Ship?' }, context); const parsed = JSON.parse((result as { stdout: string }).stdout); expect(parsed).toMatchObject({ ok: true, chairmanId: 'gamma', chairmanReason: 'top-rated', confidence: 73, degraded: false }); expect(parsed.seats).toHaveLength(2); expect(parsed.seats.every((seat: { critique: string }) => seat.critique)).toBe(true); expect(h.dispatch).toHaveBeenCalledTimes(6); expect(h.record).toHaveBeenCalled(); });
  it('honors a forced chair and reports the resulting thin panel', async () => { const h = await setup(); const result = await h.command.run({ question: 'Ship?', engines: 'alpha,beta', chairman: 'alpha' }, context); const parsed = JSON.parse((result as { stdout: string }).stdout); expect(parsed).toMatchObject({ chairmanId: 'alpha', chairmanReason: 'forced', degraded: true }); expect(parsed.seats).toHaveLength(1); });
  it('rejects a one-engine council without dispatch', async () => { const h = await setup(); const result = await h.command.run({ question: 'Ship?', engines: 'alpha' }, context); expect(result).toMatchObject({ exitCode: 1 }); expect(h.dispatch).not.toHaveBeenCalled(); });
});
