export const PIPELINE_DELIVERY_WORKFLOW = Object.freeze({
  id: 'agon.workflow.pipeline-delivery.v1',
  compatibilityAliases: Object.freeze(['tui:/pipeline', 'cesar:pipeline']),
  stages: Object.freeze(['build', 'review', 'fix']),
});

import type{AgonModFactory,CommandResult,Dispose,InvocationContext,Json,ModServices,Registrar}from'@kernlang/agon-mod-api';import{runAgentTask}from'@kernlang/agon-mod-agent';import{runReview}from'@kernlang/agon-mod-review';
const schema=Object.freeze({type:'object',additionalProperties:true,properties:{task:{type:'string'},engine:{type:'string'},engines:{type:'string'},reviewEngines:{type:'string'},timeout:{type:'string'},maxIterations:{type:'string',default:'2'},_:{type:'array',items:{type:'string'}}}})as Readonly<Record<string,Json>>;const text=(v:Json|undefined)=>typeof v==='string'?v.trim():'';
const cesarSchema=Object.freeze({type:'object',additionalProperties:false,required:['task'],properties:{task:{type:'string',minLength:1},fitnessCmd:{type:'string'},engines:{type:'array',items:{type:'string',minLength:1}}}})as Readonly<Record<string,Json>>;
const workflowMetadata=Object.freeze({workflow:{id:'agon.build-review-fix',version:'v1',alias:'agon.build-review-fix@v1',phases:['build','review','fix'],conformance:'core-workflow-registry'}}) as Json;
const FITNESS_PATTERN=/\b(?:test with|test:|--test|fitness:)\s+(.+)/i;
export function parseDeliveryPipelineIntent(value:string):Record<string,Json>|undefined{const match=value.match(/^\/(?:pipeline|pipe)(?:\s+([\s\S]*))?$/i);if(!match)return undefined;const rest=(match[1]??'').trim();const fitness=FITNESS_PATTERN.exec(rest);const fitnessCmd=fitness?fitness[1].trim():null;return{task:fitness?rest.replace(FITNESS_PATTERN,'').trim():rest,fitnessCmd};}
export async function runDeliveryPipeline(raw:Json,context:InvocationContext,services:ModServices):Promise<CommandResult>{const input=raw as Record<string,Json>;const task=text(input.task)||(Array.isArray(input._)?input._.map(String).join(' ').trim():'');if(!task)return{exitCode:1,stderr:'Delivery pipeline requires a task.\n'};const max=Math.max(1,Math.min(10,Number.parseInt(text(input.maxIterations)||'2',10)||2));const iterations:any[]=[];for(let iteration=1;iteration<=max;iteration++){const prior=iterations.at(-1)?.review?.result;const feedback=prior?`\n\nPRIOR REVIEW:\n${JSON.stringify(prior)}`:'';const built=await runAgentTask({task:`${task}${feedback}`,engine:input.engine??'',timeout:input.timeout??'600'},context,services,'agent');const review=await runReview({target:'uncommitted',engines:input.reviewEngines??input.engines??'',risk:'high',timeout:input.timeout??'420','primary-engine':text(input.engine)},context,services);iterations.push({iteration,build:{exitCode:built.exitCode,result:built.result??null},review:{exitCode:review.exitCode,result:review.result??null}});if(built.exitCode!==0)break;if(review.exitCode===0){const result={task,status:'completed',iterations};const receiptId=await services.receipts.record('pipeline-delivery',result as unknown as Json);return{exitCode:0,stdout:`${JSON.stringify({...result,receiptId},null,2)}\n`,result:{...result,receiptId}as unknown as Json};}}const result={task,status:'exhausted',iterations};const receiptId=await services.receipts.record('pipeline-delivery',result as unknown as Json);return{exitCode:1,stderr:`Delivery pipeline exhausted ${max} iteration(s). Receipt: ${receiptId}\n`,result:{...result,receiptId}as unknown as Json,failure:{code:'PIPELINE_EXHAUSTED',message:'Independent review did not pass before the iteration limit',retryable:true}};}
export const createMod:AgonModFactory=services=>Object.freeze({apiVersion:'1'as const,async activate(registrar:Registrar):Promise<Dispose>{const d:Dispose[]=[];const command={description:'Closed-loop agent build → independent review → repair',inputSchema:schema,run:(input:Json,context:InvocationContext)=>runDeliveryPipeline(input,context,services)};d.push(registrar.intent({id:'intentVariants:0045',description:'Parse pipeline intent',inputSchema:schema,parse:parseDeliveryPipelineIntent,run:command.run}));for(const id of['builtinCommandMetadata:0034','tuiSlashCommands:0050'])d.push(registrar.command('tui',{id,...command}));for(const id of['cesarRoutes:0036','cesarRoutes:0037'])d.push(registrar.planStep({id,inputSchema:schema,resultSchema:schema,risk:'workspace-write',run:(input,context)=>runDeliveryPipeline(input,context,services)}));d.push(registrar.tool('cesar',{id:'cesarTools:0016',description:'Hand this task to the build-review-fix Pipeline',inputSchema:cesarSchema,effect:'process',metadata:workflowMetadata,run:async()=> 'Delegation accepted — end your turn now so the run can start.'}));return async()=>{for(const x of[...d].reverse())await x();};}});export default createMod;
