import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import type { AgonModFactory, CommandResult, Dispose, InvocationContext, Json, ModServices, Registrar } from '@kernlang/agon-mod-api';

const home = () => resolve(process.env.AGON_HOME?.trim() || resolve(process.env.HOME || '.', '.agon'));
const runs = () => join(home(), 'runs');
const hash = (path:string) => `sha256:${createHash('sha256').update(readFileSync(path)).digest('hex')}`;
const defined = (value:Record<string,unknown>) => Object.fromEntries(Object.entries(value).filter(([,entry]) => entry !== undefined));

export function buildProvenance(manifest:any, path:string) {
  const costs = new Map<string,number>();
  for (const dispatch of manifest.dispatchLog ?? []) if (Number.isFinite(dispatch.tokens?.costUsd)) costs.set(dispatch.engineId,(costs.get(dispatch.engineId) ?? 0) + dispatch.tokens.costUsd);
  const contributions = Object.entries(manifest.results ?? {}).map(([engineId,value]) => {
    const result = value as any, winner = engineId === manifest.winner, passed = result.fitnessPassed ?? result.pass;
    return defined({engineId,role:winner?'winner':'rejected',accepted:winner,acceptanceMechanism:winner?'autonomous-gate':'not-accepted',score:result.score,passedGate:passed,
      reason:winner?'highest score among engines that passed the fitness gate':result.reason ?? (result.status && result.status !== 'ok' ? result.status : passed === false ? 'failed the fitness gate' : typeof result.score === 'number' ? `passed but lower score (${result.score})` : 'not selected'),
      diffLines:result.diffLines,filesChanged:result.filesChanged,durationSec:result.durationSec,costUsd:costs.has(engineId)?Math.round(costs.get(engineId)!*10000)/10000:undefined});
  });
  for (const skipped of manifest.skippedEngines ?? []) contributions.push(defined({engineId:skipped.engineId,role:'skipped',accepted:false,acceptanceMechanism:'not-accepted',reason:skipped.reason ?? skipped.status}));
  const blended = Boolean(manifest.synthesis?.wins);
  if (manifest.synthesis) contributions.push(defined({engineId:manifest.winner ?? 'synthesis',role:'synthesizer',accepted:blended,acceptanceMechanism:blended?'machine-synthesized-blend':'not-accepted',score:manifest.synthesis.score,passedGate:manifest.synthesis.pass,reason:blended?`synthesis improved on the winner (${manifest.synthesis.originalWinnerScore ?? '?'} -> ${manifest.synthesis.score})`:'synthesis did not beat the winner; the winner patch was kept'}));
  return {schemaVersion:1,kind:'forge',generatedAt:new Date().toISOString(),runId:manifest.forgeId,humanPrompt:manifest.task,gate:manifest.fitnessCmd,startedAt:manifest.timestamp,engines:manifest.engines ?? [],contributions,winner:manifest.winner ?? null,autonomyLevel:'autonomous-selection',synthesisBlended:blended,sourceHashes:{'manifest.json':hash(path)},aiDidNot:['choose which problem to solve — the task was specified by the human','define the success criterion — the fitness command was provided by the human',...(manifest.winner?['decide final adoption — whether the winning patch was committed or merged is not recorded for this run']:[])],limitations:['Engine outputs are non-deterministic; re-running may produce different results.','Rejection reasons reflect the recorded gate/score/status, not a judgment of code quality.','No per-token, line-level authorship attribution is claimed.',...(blended?['The accepted patch is a synthesis blend of multiple engines; single-engine authorship cannot be claimed.']:[])],responsibility:'This report discloses how AI engines were used. The human author retains full responsibility for any output adopted into their work.'};
}
const one = (value:unknown) => String(value ?? '').replace(/\r?\n+/g,' ').trim();
const cell = (value:unknown) => one(value).replace(/\|/g,'\\|');
export function renderMarkdown(ledger:any):string {
  const lines = ['# AI Contribution Statement','',`Generated by Agon · ${ledger.generatedAt}`,`Run: \`${ledger.runId}\` (${ledger.kind})`,`Started: ${ledger.startedAt}`,'','## Scope',`- **Task (authored by the human):** ${one(ledger.humanPrompt)}`];
  if (ledger.gate) lines.push(`- **Success criterion (defined by the human):** \`${one(ledger.gate)}\``);
  lines.push(`- **Engines consulted:** ${ledger.engines.length ? ledger.engines.join(', ') : '—'}`,'- **Autonomy level:** AI-SELECTED (the winner was chosen automatically by the fitness gate)','','## Contributions','','| Engine | Role | Accepted | How | Score | Reason |','| --- | --- | --- | --- | --- | --- |');
  for (const contribution of ledger.contributions) lines.push(`| ${cell(contribution.engineId)} | ${contribution.role} | ${contribution.accepted?'yes':'no'} | ${contribution.acceptanceMechanism} | ${contribution.score ?? '—'} | ${cell(contribution.reason ?? '—')} |`);
  lines.push('','## What the AI did NOT do',...ledger.aiDidNot.map((value:string)=>`- ${value}`),'','## Limitations',...ledger.limitations.map((value:string)=>`- ${value}`),'','## Source integrity',...Object.entries(ledger.sourceHashes).map(([key,value])=>`- \`${key}\`: ${value}`),'','## Responsibility',ledger.responsibility,'');
  return lines.join('\n');
}
function pick(id:string):{file:string}|{error:string} {
  let files:string[];
  try { files = readdirSync(runs()).filter((file)=>file.endsWith('.json')).sort().reverse(); } catch { return {error:'No forge runs yet.'}; }
  if (!files.length) return {error:'No forge runs yet.'};
  if (!id) return {file:files[0]};
  const prefix = files.filter((file)=>file.startsWith(id)), matches = prefix.length ? prefix : files.filter((file)=>file.includes(id));
  if (!matches.length) return {error:`Run "${id}" not found`};
  if (matches.length > 1) return {error:`Run prefix "${id}" is ambiguous`};
  return {file:matches[0]};
}
export async function runProvenance(raw:Json, _context:InvocationContext, services:ModServices):Promise<CommandResult> {
  const input = raw as Record<string,Json>, id = String(input.id ?? (Array.isArray(input._) ? input._[0] : '')).trim(), format = String(input.format ?? 'md').toLowerCase();
  if (!['md','json','both'].includes(format)) return {exitCode:1,stderr:'Unknown format. Use md, json, or both.\n'};
  const selected = pick(id); if ('error' in selected) return {exitCode:1,stderr:selected.error+'\n'};
  const manifestPath = join(runs(),selected.file); let manifest:any;
  try { manifest = JSON.parse(readFileSync(manifestPath,'utf8')); } catch (error) { return {exitCode:1,stderr:`Could not read run: ${String(error)}\n`}; }
  if (typeof manifest.forgeId !== 'string' || typeof manifest.task !== 'string') return {exitCode:1,stderr:'Run is not a valid forge manifest.\n'};
  const ledger = buildProvenance(manifest,manifestPath), markdown = renderMarkdown(ledger), json = JSON.stringify(ledger,null,2);
  const payload = format === 'json' ? json : format === 'both' ? `${markdown}\n\n--- JSON LEDGER ---\n\n${json}\n` : markdown;
  const out = typeof input.out === 'string' ? resolve(input.out) : '';
  if (out) {
    if (await services.permissions.check('fs.write',out) !== 'allow') return {exitCode:1,stderr:'Permission denied: fs.write is required.\n'};
    mkdirSync(dirname(out),{recursive:true}); const temporary = `${out}.tmp.${process.pid}`; writeFileSync(temporary,payload); renameSync(temporary,out);
  }
  const receiptId = await services.receipts.record('provenance-read',{runId:manifest.forgeId,sourceHash:ledger.sourceHashes['manifest.json'],format,written:out || null});
  const result = JSON.parse(JSON.stringify({ledger,format,out:out || null,receiptId})) as Json;
  return {exitCode:0,stdout:out?`Provenance report written to ${out}\n`:`${payload}\n`,result};
}
const schema = Object.freeze({type:'object',additionalProperties:false,properties:{id:{type:'string'},format:{type:'string',default:'md'},out:{type:'string'},_:{type:'array',items:{type:'string'}}}}) as Readonly<Record<string,Json>>;
const cli = Object.freeze({aliases:{format:'f',out:'o'}});
export const createMod:AgonModFactory = (services) => Object.freeze({apiVersion:'1' as const,async activate(registrar:Registrar):Promise<Dispose>{
  const disposers:Dispose[] = [], contribution = {id:'cliCommands:0057',description:'AI-contribution / transparency report for a forge run',inputSchema:schema,cli,run:(input:Json,context:InvocationContext)=>runProvenance(input,context,services)};
  disposers.push(registrar.command('cli',contribution)); disposers.push(registrar.command('tui',{...contribution,id:'builtinCommandMetadata:0037'}));
  return async()=>{for(const dispose of [...disposers].reverse())await dispose();};
}});
export default createMod;
