#!/usr/bin/env bash
# Mock engine for testing — simulates an AI CLI tool
# Usage: mock-engine.sh [--version | --print PROMPT]

case "${1:-}" in
  --version)
    echo "mock-engine 1.0.0"
    ;;
  --print|--auto|--approval-mode)
    # Simulate code generation: create a simple file
    echo "// Generated by mock engine"
    echo 'export function hello() { return "world"; }'

    # If running in a cwd, write a file
    if [ -n "${AGON_CWD:-}" ]; then
      echo 'export function hello() { return "world"; }' > "${AGON_CWD}/generated.ts"
    fi
    ;;
  *)
    echo "Usage: mock-engine.sh [--version | --print PROMPT]"
    exit 1
    ;;
esac
