import { execFileSync } from 'node:child_process';
import type { AgonModFactory, CommandResult, Dispose, InvocationContext, Json, ModServices, Registrar } from '@kernlang/agon-mod-api';

const schema=Object.freeze({type:'object',additionalProperties:true,properties:{action:{type:'string',enum:['commit','undo']},message:{type:'string'},approved:{type:'boolean'},expectedHead:{type:'string'},_:{type:'array',items:{type:'string'}}}})as Readonly<Record<string,Json>>;
const git=(cwd:string,args:string[])=>execFileSync('git',args,{cwd,encoding:'utf8',timeout:30_000,stdio:['ignore','pipe','pipe']}).trim();
const fail=(message:string,code='GIT_ACTION_REFUSED'):CommandResult=>({exitCode:1,stderr:`${message}\n`,failure:{code,message,retryable:false}});

/** Explicit mutation API: staged bytes and operator-authored message only; never pushes. */
export async function runGitAction(raw:Json,context:InvocationContext,services:ModServices,defaultAction?:'commit'|'undo'):Promise<CommandResult>{const input=raw as Record<string,Json>;const action=defaultAction??(String(input.action??'commit')as'commit'|'undo');if(input.approved!==true)return fail(`${action} requires approved=true from an explicit operator gate`,'APPROVAL_REQUIRED');const permission=await services.permissions.check('git.write',context.cwd);if(permission!=='allow')return fail(`git.write permission is ${permission}`,'PERMISSION_DENIED');
  let head:string;try{head=git(context.cwd,['rev-parse','HEAD']);}catch{return fail('Current working directory is not a Git repository');}const expected=String(input.expectedHead??'').trim();if(expected&&expected!==head)return fail(`HEAD changed: expected ${expected}, found ${head}`,'STALE_GIT_HEAD');
  try{if(action==='commit'){const message=String(input.message??'').trim();if(!message)return fail('Commit requires an operator-authored message');if(/(?:^|\n)\s*(?:Co-Authored-By|Co-authored-by):/i.test(message))return fail('Authorship trailers are not accepted by the modular Git action');const staged=git(context.cwd,['diff','--cached','--name-only']);if(!staged)return fail('Nothing is staged; modular commit never stages files implicitly');git(context.cwd,['commit','-m',message]);const commit=git(context.cwd,['rev-parse','HEAD']);const result={action,previousHead:head,head:commit,message,stagedFiles:staged.split('\n').filter(Boolean)};const receiptId=await services.receipts.record('git-commit',result as unknown as Json);return{exitCode:0,stdout:`${JSON.stringify({...result,receiptId},null,2)}\n`,result:{...result,receiptId}as unknown as Json};}
    const dirty=git(context.cwd,['status','--porcelain']);if(dirty)return fail('Undo requires a clean working tree and index');const parent=git(context.cwd,['rev-parse','HEAD^']);git(context.cwd,['reset','--soft',parent]);const result={action,previousHead:head,head:parent,changesRemainStaged:true};const receiptId=await services.receipts.record('git-undo',result as unknown as Json);return{exitCode:0,stdout:`${JSON.stringify({...result,receiptId},null,2)}\n`,result:{...result,receiptId}as unknown as Json};
  }catch(error:any){const message=String(error?.stderr??error?.message??error).trim();return fail(message||`Git ${action} failed`,'GIT_ACTION_FAILED');}}

const actions:Record<string,'commit'|'undo'>={'intentVariants:0017':'commit','intentVariants:0064':'undo','builtinCommandMetadata:0013':'commit','builtinCommandMetadata:0049':'undo','tuiSlashCommands:0018':'commit','tuiSlashCommands:0070':'undo'};
export const createMod:AgonModFactory=services=>Object.freeze({apiVersion:'1'as const,async activate(registrar:Registrar):Promise<Dispose>{const d:Dispose[]=[];for(const[id,action]of Object.entries(actions)){const contribution={id,description:`Explicit permission-checked Git ${action}`,inputSchema:schema,run:(input:Json,context:InvocationContext)=>runGitAction(input,context,services,action)};if(id.startsWith('intentVariants:'))d.push(registrar.intent({...contribution,parse:value=>{if(!(value.toLowerCase().startsWith(`/${action}`)||value.toLowerCase().startsWith(action)))return undefined;const rest=value.replace(new RegExp(`^/?${action}\\s*`,'i'),'').trim();if(action==='undo'){const parts=rest.split(/\s+/).filter(Boolean);return{snapshotId:parts[0]==='checkpoint'?parts[1]:parts[0]};}return{input:rest||undefined,message:rest};}}));else d.push(registrar.command('tui',contribution));}return async()=>{for(const dispose of[...d].reverse())await dispose();};}});export default createMod;
