import { afterEach, describe, expect, it } from 'vitest';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { addKernSourceTraces } from '../../scripts/kern-source-traces.mjs';

const tempRoots: string[] = [];

function makeTempRoot() {
  const root = mkdtempSync(path.join(tmpdir(), 'agon-kern-source-traces-'));
  tempRoots.push(root);
  return root;
}

function writeFile(filePath: string, content: string) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, content);
}

afterEach(() => {
  for (const root of tempRoots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
});

describe('kern source traces', () => {
  it('annotates generated declarations from matching .kern source nodes', () => {
    const root = makeTempRoot();
    const srcDir = path.join(root, 'src/kern');
    const outDir = path.join(root, 'src/generated');

    writeFile(
      path.join(srcDir, 'demo.kern'),
      [
        'const name=COUNT type=number',
        '  handler <<<',
        '    1',
        '  >>>',
        '',
        'fn name=hello params="" returns="string"',
        '  handler <<<',
        '    return "hi";',
        '  >>>',
      ].join('\n'),
    );
    writeFile(
      path.join(outDir, 'demo.ts'),
      [
        '// @generated by kern v3.3.9 — DO NOT EDIT. Source: src/kern/demo.kern',
        '',
        'export const COUNT: number = 1;',
        '',
        'export function hello(): string {',
        '  return "hi";',
        '}',
      ].join('\n'),
    );

    expect(addKernSourceTraces(srcDir, outDir)).toEqual({ files: 1, updated: 1 });

    const generated = readFileSync(path.join(outDir, 'demo.ts'), 'utf8');
    expect(generated).toContain('// @kern-source: demo:1\nexport const COUNT');
    expect(generated).toContain('// @kern-source: demo:6\nexport function hello');
  });

  it('adds a header fallback for generated entry files without matching declarations', () => {
    const root = makeTempRoot();
    const srcDir = path.join(root, 'src/kern');
    const outDir = path.join(root, 'src/generated');

    writeFile(
      path.join(srcDir, 'screen.kern'),
      [
        'screen name=AgonCli target=ink',
        '  render',
        '    handler <<<',
        '      return null;',
        '    >>>',
      ].join('\n'),
    );
    writeFile(
      path.join(outDir, 'screen.entry.tsx'),
      [
        '#!/usr/bin/env node',
        '// @generated by kern v3.3.9 — DO NOT EDIT. Source: src/kern/screen.kern',
        '',
        "import { render } from 'ink';",
        'render(null);',
      ].join('\n'),
    );

    expect(addKernSourceTraces(srcDir, outDir)).toEqual({ files: 1, updated: 1 });

    const generated = readFileSync(path.join(outDir, 'screen.entry.tsx'), 'utf8');
    expect(generated).toContain(
      [
        '#!/usr/bin/env node',
        '// @generated by kern v3.3.9 — DO NOT EDIT. Source: src/kern/screen.kern',
        '',
        '// @kern-source: screen:1',
      ].join('\n'),
    );
  });

  it('does not duplicate existing source trace comments', () => {
    const root = makeTempRoot();
    const srcDir = path.join(root, 'src/kern');
    const outDir = path.join(root, 'src/generated');

    writeFile(
      path.join(srcDir, 'demo.kern'),
      [
        'fn name=hello params="" returns="string"',
        '  handler <<<',
        '    return "hi";',
        '  >>>',
      ].join('\n'),
    );
    writeFile(
      path.join(outDir, 'demo.ts'),
      [
        '// @generated by kern v3.3.9 — DO NOT EDIT. Source: src/kern/demo.kern',
        '',
        '// @kern-source: demo:1',
        'export function hello(): string {',
        '  return "hi";',
        '}',
      ].join('\n'),
    );

    expect(addKernSourceTraces(srcDir, outDir)).toEqual({ files: 1, updated: 0 });
  });
});
