import { afterEach, describe, expect, it } from 'vitest';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  installKernStackTraceMapper,
  mapKernStackTrace,
  resolveKernSourceLocation,
  uninstallKernStackTraceMapper,
} from '../../packages/core/src/index.js';

const require = createRequire(import.meta.url);
const nodeModule = require('node:module') as any;
const tempRoots: string[] = [];
const originalPrepareStackTrace = Error.prepareStackTrace;
const originalDisableEnv = process.env.AGON_NO_STACK_TRACE_MAPPER;

function makeTempRoot() {
  const root = mkdtempSync(path.join(tmpdir(), 'agon-kern-stack-trace-'));
  tempRoots.push(root);
  return root;
}

function writeFile(filePath: string, content: string) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, content);
}

afterEach(() => {
  uninstallKernStackTraceMapper();
  Error.prepareStackTrace = originalPrepareStackTrace;
  if (originalDisableEnv === undefined) {
    delete process.env.AGON_NO_STACK_TRACE_MAPPER;
  } else {
    process.env.AGON_NO_STACK_TRACE_MAPPER = originalDisableEnv;
  }
  for (const root of tempRoots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
});

describe('kern stack trace mapping', () => {
  it('resolves generated TypeScript frames to the nearest KERN source trace', () => {
    const root = makeTempRoot();
    const generatedPath = path.join(root, 'src/generated/blocks/demo.ts');
    const kernPath = path.join(root, 'src/kern/blocks/demo.kern');
    writeFile(kernPath, 'fn name=hello params="" returns=void\n');
    writeFile(
      generatedPath,
      [
        '// @generated by kern v3.5.7 - DO NOT EDIT. Source: src/kern/blocks/demo.kern',
        '',
        '// @kern-source: demo:1',
        'export function hello(): void {',
        '  throw new Error("boom");',
        '}',
      ].join('\n'),
    );

    expect(resolveKernSourceLocation(generatedPath, 5, 9)).toEqual({
      file: kernPath,
      line: 1,
      sourceName: 'demo',
      generatedFile: generatedPath,
      generatedLine: 5,
    });
  });

  it('appends KERN source hints to stack lines without removing runtime frames', () => {
    const root = makeTempRoot();
    const generatedPath = path.join(root, 'src/generated/blocks/demo.ts');
    const kernPath = path.join(root, 'src/kern/blocks/demo.kern');
    writeFile(kernPath, 'fn name=hello params="" returns=void\n');
    writeFile(
      generatedPath,
      [
        '// @generated by kern v3.5.7 - DO NOT EDIT. Source: src/kern/blocks/demo.kern',
        '',
        '// @kern-source: demo:1',
        'export function hello(): void {',
        '  throw new Error("boom");',
        '}',
      ].join('\n'),
    );

    const mapped = mapKernStackTrace(`Error: boom\n    at hello (${generatedPath}:5:9)`);

    expect(mapped).toContain(`${generatedPath}:5:9`);
    expect(mapped).toContain(`[kern: ${kernPath}:1]`);
  });

  it('maps generated stack lines whose paths contain spaces and parentheses', () => {
    const root = makeTempRoot();
    const generatedPath = path.join(root, 'src/generated/blocks/dir with space (demo)/demo.ts');
    const kernPath = path.join(root, 'src/kern/blocks/demo.kern');
    writeFile(kernPath, 'fn name=hello params="" returns=void\n');
    writeFile(
      generatedPath,
      [
        '// @generated by kern v3.5.7 - DO NOT EDIT. Source: src/kern/blocks/demo.kern',
        '',
        '// @kern-source: demo:5',
        'export function hello(): void {',
        '  throw new Error("boom");',
        '}',
      ].join('\n'),
    );

    const mapped = mapKernStackTrace(`Error: boom\n    at hello (${generatedPath}:5:9)`);

    expect(mapped).toContain(`${generatedPath}:5:9`);
    expect(mapped).toContain(`[kern: ${kernPath}:5]`);
  });

  it('uses sibling source maps and sourcesContent for bundled frames', () => {
    const root = makeTempRoot();
    const distPath = path.join(root, 'dist/index.js');
    const kernPath = path.join(root, 'src/kern/blocks/demo.kern');
    const generatedSourcePath = '../src/generated/blocks/demo.ts';
    const generatedSourceContent = [
      '// @generated by kern v3.5.7 - DO NOT EDIT. Source: src/kern/blocks/demo.kern',
      '// @kern-source: demo:7',
      'export function hello(): void { throw new Error("boom"); }',
    ].join('\n');

    writeFile(kernPath, 'fn name=hello params="" returns=void\n');
    writeFile(distPath, '\nthrow new Error("boom");\n//# sourceMappingURL=index.js.map\n');
    writeFile(
      `${distPath}.map`,
      JSON.stringify({
        version: 3,
        file: 'index.js',
        sources: [generatedSourcePath],
        sourcesContent: [generatedSourceContent],
        names: [],
        mappings: ';AACA',
        sourceRoot: '',
      }),
    );

    const mapped = mapKernStackTrace(`Error: boom\n    at hello (${distPath}:2:1)`);

    expect(mapped).toContain(`${distPath}:2:1`);
    expect(mapped).toContain(`[kern: ${kernPath}:7]`);
    expect(readFileSync(`${distPath}.map`, 'utf8')).toContain(generatedSourcePath);
  });

  it('uses findEntry-compatible source maps when findOrigin is unavailable', () => {
    const sourceMapProto = nodeModule.SourceMap?.prototype;
    expect(sourceMapProto?.findEntry).toBeTypeOf('function');
    const originalFindOrigin = sourceMapProto.findOrigin;
    sourceMapProto.findOrigin = undefined;

    try {
      const root = makeTempRoot();
      const distPath = path.join(root, 'dist/index.js');
      const kernPath = path.join(root, 'src/kern/blocks/demo.kern');
      const generatedSourcePath = '../src/generated/blocks/demo.ts';
      const generatedSourceContent = [
        '// @generated by kern v3.5.7 - DO NOT EDIT. Source: src/kern/blocks/demo.kern',
        '// @kern-source: demo:11',
        'export function hello(): void { throw new Error("boom"); }',
      ].join('\n');

      writeFile(kernPath, 'fn name=hello params="" returns=void\n');
      writeFile(distPath, '\nthrow new Error("boom");\n//# sourceMappingURL=index.js.map\n');
      writeFile(
        `${distPath}.map`,
        JSON.stringify({
          version: 3,
          file: 'index.js',
          sources: [generatedSourcePath],
          sourcesContent: [generatedSourceContent],
          names: [],
          mappings: ';AACA',
          sourceRoot: '',
        }),
      );

      const mapped = mapKernStackTrace(`Error: boom\n    at hello (${distPath}:2:1)`);

      expect(mapped).toContain(`[kern: ${kernPath}:11]`);
    } finally {
      sourceMapProto.findOrigin = originalFindOrigin;
    }
  });

  it('uses block-comment source map URLs with literal stars', () => {
    const root = makeTempRoot();
    const distPath = path.join(root, 'dist/index.js');
    const mapPath = path.join(root, 'dist/index.js*.map');
    const kernPath = path.join(root, 'src/kern/blocks/demo.kern');
    const generatedSourcePath = '../src/generated/blocks/demo.ts';
    const generatedSourceContent = [
      '// @generated by kern v3.5.7 - DO NOT EDIT. Source: src/kern/blocks/demo.kern',
      '// @kern-source: demo:13',
      'export function hello(): void { throw new Error("boom"); }',
    ].join('\n');

    writeFile(kernPath, 'fn name=hello params="" returns=void\n');
    writeFile(distPath, '\nthrow new Error("boom");\n/*# sourceMappingURL=index.js*.map */\n');
    writeFile(
      mapPath,
      JSON.stringify({
        version: 3,
        file: 'index.js',
        sources: [generatedSourcePath],
        sourcesContent: [generatedSourceContent],
        names: [],
        mappings: ';AACA',
        sourceRoot: '',
      }),
    );

    const mapped = mapKernStackTrace(`Error: boom\n    at hello (${distPath}:2:1)`);

    expect(mapped).toContain(`[kern: ${kernPath}:13]`);
  });

  it('installs idempotently and composes with an existing prepareStackTrace', () => {
    const root = makeTempRoot();
    const generatedPath = path.join(root, 'src/generated/blocks/demo.ts');
    const kernPath = path.join(root, 'src/kern/blocks/demo.kern');
    writeFile(kernPath, 'fn name=hello params="" returns=void\n');
    writeFile(
      generatedPath,
      [
        '// @generated by kern v3.5.7 - DO NOT EDIT. Source: src/kern/blocks/demo.kern',
        '',
        '// @kern-source: demo:3',
        'export function hello(): void {',
        '  throw new Error("boom");',
        '}',
      ].join('\n'),
    );

    let previousCalls = 0;
    const previousPrepare = () => {
      previousCalls += 1;
      return `CustomError: boom\n    at hello (${generatedPath}:5:9)`;
    };
    Error.prepareStackTrace = previousPrepare;

    installKernStackTraceMapper();
    const firstWrapper = Error.prepareStackTrace;
    installKernStackTraceMapper();

    expect(Error.prepareStackTrace).toBe(firstWrapper);
    expect(new Error('boom').stack).toContain(`[kern: ${kernPath}:3]`);
    expect(previousCalls).toBe(1);

    uninstallKernStackTraceMapper();
    expect(Error.prepareStackTrace).toBe(previousPrepare);
  });

  it('wraps the current prepareStackTrace when another wrapper replaces it', () => {
    const previousPrepare = () => 'previous stack';
    const externalPrepare = () => 'external stack';
    Error.prepareStackTrace = previousPrepare;

    installKernStackTraceMapper();
    const firstWrapper = Error.prepareStackTrace;
    expect(firstWrapper).not.toBe(previousPrepare);

    Error.prepareStackTrace = externalPrepare;
    installKernStackTraceMapper();

    expect(Error.prepareStackTrace).not.toBe(externalPrepare);
    expect(Error.prepareStackTrace).not.toBe(firstWrapper);
    uninstallKernStackTraceMapper();
    expect(Error.prepareStackTrace).toBe(externalPrepare);
  });

  it('does not install when AGON_NO_STACK_TRACE_MAPPER is set', () => {
    const previousPrepare = () => 'custom stack';
    Error.prepareStackTrace = previousPrepare;
    process.env.AGON_NO_STACK_TRACE_MAPPER = '1';

    installKernStackTraceMapper();

    expect(Error.prepareStackTrace).toBe(previousPrepare);
  });

  it('does not throw when prepareStackTrace assignment is rejected', () => {
    const descriptor = Object.getOwnPropertyDescriptor(Error, 'prepareStackTrace');
    const previousPrepare = () => 'custom stack';
    Object.defineProperty(Error, 'prepareStackTrace', {
      configurable: true,
      get: () => previousPrepare,
      set: () => {
        throw new Error('prepareStackTrace is read-only');
      },
    });

    try {
      expect(() => installKernStackTraceMapper()).not.toThrow();
      expect(Error.prepareStackTrace).toBe(previousPrepare);
    } finally {
      if (descriptor) {
        Object.defineProperty(Error, 'prepareStackTrace', descriptor);
      } else {
        delete (Error as any).prepareStackTrace;
      }
    }
  });

  it('does not throw when uninstall cannot restore prepareStackTrace', () => {
    Error.prepareStackTrace = () => 'previous stack';
    installKernStackTraceMapper();
    const wrapper = Error.prepareStackTrace;
    const descriptor = Object.getOwnPropertyDescriptor(Error, 'prepareStackTrace');
    Object.defineProperty(Error, 'prepareStackTrace', {
      configurable: true,
      get: () => wrapper,
      set: () => {
        throw new Error('prepareStackTrace is read-only');
      },
    });

    try {
      expect(() => uninstallKernStackTraceMapper()).not.toThrow();
    } finally {
      if (descriptor) {
        Object.defineProperty(Error, 'prepareStackTrace', descriptor);
      } else {
        delete (Error as any).prepareStackTrace;
      }
    }
  });
});
