import type { AgonModFactory, CommandResult, Dispose, Json, ModServices, RankedEngine, Registrar } from '@kernlang/agon-mod-api';

const schema = Object.freeze({ type: 'object', additionalProperties: true, properties: { decision: { type: 'string' }, reasoning: { type: 'string' }, focus: { type: 'string' }, confidence: { type: 'string' }, engine: { type: 'string' }, engines: { type: 'string' }, timeout: { type: 'string', default: '120' }, json: { type: 'boolean' }, quiet: { type: 'boolean' }, label: { type: 'string' }, _: { type: 'array', items: { type: 'string' } } } }) as Readonly<Record<string, Json>>;
const cesarSchema = Object.freeze({ type: 'object', additionalProperties: false, properties: { reason: { type: 'string' } } }) as Readonly<Record<string, Json>>;
const cli = Object.freeze({ positionals: ['decision'], aliases: { engines: 'e' }, descriptions: { decision: 'Decision, plan, or answer to challenge' } });
const text = (value: unknown) => typeof value === 'string' ? value.trim() : '';
const extras = (value: unknown) => Array.isArray(value) ? value.map(String) : [];
const ids = (value: Json | undefined) => typeof value === 'string' ? value.split(',').map((id) => id.trim()).filter(Boolean) : [];
type Verdict = 'flawed' | 'proceed-with-caution' | 'sound' | 'unknown';
function verdict(value: string): Verdict { const found = [...value.matchAll(/VERDICT:\s*(FLAWED|PROCEED WITH CAUTION|SOUND)/gi)].at(-1)?.[1].toUpperCase(); return found === 'FLAWED' ? 'flawed' : found === 'SOUND' ? 'sound' : found === 'PROCEED WITH CAUTION' ? 'proceed-with-caution' : 'unknown'; }
function confidence(value: string): number | null { const match = value.match(/confidence[:\s]*~?\s*(\d{1,3})\s*%/i) ?? value.match(/~?\s*(\d{1,3})\s*%/); if (!match) return null; const n = Number(match[1]); return n >= 0 && n <= 100 ? n : null; }
function prompt(input: Record<string, Json>, decision: string): string { return [`You are Nero — a structurally adversarial reviewer. Find why this reasoning is wrong.`, `DECISION UNDER REVIEW:\n${decision}`, text(input.reasoning) ? `STATED REASONING:\n${text(input.reasoning)}` : '', text(input.confidence) ? `AUTHOR'S CONFIDENCE: ${text(input.confidence)}%` : '', text(input.focus) ? `FOCUS: ${text(input.focus)}` : '', 'Give at most five concrete failure scenarios using INVERSION, PRE-MORTEM, or SECOND-ORDER reasoning.', 'Begin with "Confidence: X%" (confidence the original is correct).', 'End with exactly one: VERDICT: FLAWED, VERDICT: PROCEED WITH CAUTION, or VERDICT: SOUND.'].filter(Boolean).join('\n\n'); }

export async function runNero(raw: Json, context: Parameters<ModServices['engines']['dispatch']>[2], services: ModServices): Promise<CommandResult> {
  const input = raw as Record<string, Json>; const decision = [text(input.decision), ...extras(input._).filter((part) => part !== input.decision)].filter(Boolean).join(' ').trim(); if (!decision) return { exitCode: 1, stderr: 'Provide a decision to challenge. Usage: agon nero "your decision"\n' };
  const active = services.engines.listActive ? [...await services.engines.listActive(context)] : []; const requested = ids(input.engines); let pool = requested.length ? requested : active; const forced = text(input.engine);
  const unknown = pool.filter((id) => active.length && !active.includes(id)); if (unknown.length) return { exitCode: 1, stderr: `Unknown or inactive engine${unknown.length > 1 ? 's' : ''}: ${unknown.join(', ')}\n` }; if (forced && active.length && !active.includes(forced)) return { exitCode: 1, stderr: `Unknown or inactive engine: ${forced}\n` }; if (forced) pool = [forced]; pool = [...new Set(pool)]; if (!pool.length) return { exitCode: 1, stderr: 'No active engine can play Nero.\n' };
  let ranked: readonly RankedEngine[] = pool.map((engineId) => ({ engineId, reason: 'random' as const, scope: null })); if (!forced && services.engines.rank) ranked = await services.engines.rank(pool, ['critique', 'tribunal'], context); if (forced) ranked = [{ engineId: forced, reason: 'top-rated', scope: null }];
  const timeoutSeconds = Math.max(1, Number.parseInt(text(input.timeout) || '120', 10)); const attempts: { engineId: string; attempt: number; error: string }[] = []; let lastText = '';
  for (const critic of ranked) { for (let attempt = 1; attempt <= 2; attempt++) { if (context.signal.aborted) return { exitCode: 1, stderr: 'Nero aborted before a verdict.\n' }; try { const output = await services.engines.dispatch(critic.engineId, prompt(input, decision), context, { timeoutSeconds: attempt === 1 ? timeoutSeconds : Math.max(1, Math.floor(timeoutSeconds / 2)), systemPrompt: 'You are an adversarial critic. Respond directly. Do not use tools.' }) as Record<string, Json>; lastText = text(output.stdout).replace(/<think>[\s\S]*?<\/think>\s*/gi, '').trim(); const parsed = verdict(lastText); if (output.exitCode === 0 && output.timedOut !== true && lastText && parsed !== 'unknown') { const result = { ok: true, engineId: critic.engineId, reason: forced ? 'forced' : critic.reason, scope: critic.scope, verdict: parsed, challengeConfidence: confidence(lastText), challengeText: lastText, attempts }; await services.receipts.record('nero', { engineId: critic.engineId, verdict: parsed, attempts: attempts.length + 1 }); const stdout = input.quiet === true ? `${parsed.toUpperCase()} — ${critic.engineId}\n` : `${JSON.stringify(result, null, 2)}\n`; return { exitCode: 0, stdout, result: result as Json }; } const why = output.timedOut === true ? 'timed out' : !lastText ? text(output.stderr) || 'empty response' : 'no parseable verdict'; attempts.push({ engineId: critic.engineId, attempt, error: why }); if (lastText && parsed === 'unknown') break; } catch (error) { attempts.push({ engineId: critic.engineId, attempt, error: error instanceof Error ? error.message : String(error) }); } } }
  const result = { ok: false, engineId: ranked.at(-1)?.engineId ?? '', reason: 'none', scope: null, verdict: 'unknown', challengeConfidence: confidence(lastText), challengeText: lastText || 'No critic produced a valid verdict.', attempts }; return { exitCode: 1, stderr: 'Nero produced no usable challenge.\n', result: result as Json };
}

export const createMod: AgonModFactory = (services) => Object.freeze({ apiVersion: '1' as const, async activate(registrar: Registrar): Promise<Dispose> { const d: Dispose[] = []; const command = { description: 'Adversarial self-challenge with concrete failure scenarios and a verdict', inputSchema: schema, cli, run: (input: Json, context: any) => runNero(input, context, services) }; d.push(registrar.command('cli', { id: 'cliCommands:0056', ...command })); d.push(registrar.intent({ id: 'intentVariants:0042', description: 'Parse Nero intent', inputSchema: schema, parse: (input) => { if(!/^\/(?:nero|devil|adversarial)(?:\s|$)/i.test(input))return undefined;const rest=input.replace(/^\/(?:nero|devil|adversarial)\s*/i,'').trim();if(!rest)return{type:'nero'};const marker=rest.match(/\s+--reasoning\s+/i);return{type:'nero-challenge',input:marker?rest.slice(0,marker.index).trim():rest,...(marker?{reasoning:rest.slice((marker.index??0)+marker[0].length).trim()}:{})}; }, run: (input, context) => runNero(input, context, services) })); for (const id of ['builtinCommandMetadata:0033', 'tuiSlashCommands:0047']) d.push(registrar.command('tui', { id, ...command })); d.push(registrar.tool('mcp', { id: 'mcpTools:0019', description: 'Challenge a decision adversarially', inputSchema: schema, effect: 'process', run: async (input, context) => (await runNero(input, context, services)).result ?? {} })); d.push(registrar.tool('cesar', { id: 'cesarTools:0018', description: 'Schedule a Quick Nero self-check after the current tool loop', inputSchema: cesarSchema, effect: 'read', run: async () => 'Quick Nero self-check scheduled. Continue responding — the self-check runs after the tool loop.' })); return async () => { for (const dispose of [...d].reverse()) await dispose(); }; } }); export default createMod;
